
<!-- begin page content -->
<div class="page_content clearfix">
	<a rel="prettyPhoto" href="images/defaults/big_1.jpg"><img class="img_bottom" src="images/defaults/full_1.jpg" alt="" width="100%" height="200" /></a>
	<h2>Project 1</h2>
	<p>On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater.</p>
	<h2>The standard Lorem Ipsum passage, used since the 1500s</h2>
	<p>Quisque nec lacus ante, nec consectetur nisi. In faucibus vestibulum vehicula. Donec luctus quam sed sapien mollis mollis placerat dui rutrum. In vel sagittis nisi. Quisque condimentum, augue vitae egestas suscipit, lectus erat facilisis risus, non luctus dui arcu nec nunc. Nulla elementum tempus tortor et iaculis. Praesent eu felis nec mi pretium interdum. Ut augue neque, ullamcorper posuere malesuada ac, sodales eget mi. Nullam ullamcorper venenatis ligula. Vivamus commodo dui ut leo iaculis ultricies sit amet non elit. Suspendisse nunc erat, aliquet nec accumsan ut, suscipit in leo. Vestibulum leo massa, pretium quis cursus vitae, tempus nec lorem. Morbi in ligula augue. </p>
	<a rel="prettyPhoto" href="images/defaults/big_1.jpg"><img class="img_left" src="images/defaults/simple_1.jpg" alt="" width="125" height="337" align="left" /></a>
	<h2>Section 1.10.32 of "de Finibus Bonorum et Malorum"</h2>
	<p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla"</p>
	<h2>Everything you see here</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fermentum mattis massa, ac rhoncus turpis malesuada at. Quisque purus orci, pretium id tincidunt sed, pharetra sit amet massa. Aenean condimentum arcu a ante faucibus blandit. Sed pellentesque ornare lorem, vel adipiscing nibh molestie nec. Suspendisse vitae diam turpis. Integer eu neque odio, in interdum arcu. Nunc ultricies ullamcorper mi id pellentesque. Nam felis dolor, vulputate ut vehicula in, aliquam eu elit. Etiam in nulla neque. Duis laoreet auctor mauris at sollicitudin. Sed feugiat erat eu dui euismod adipiscing.</p>

</div>
<!-- end page content -->